coverage:
  status:
    project:
      default:
        target: auto
      python:
        target: auto
        flags:
          - python
      php:
        target: auto
        flags:
          - php
      javascript:
        target: auto
        flags:
          - javascript
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null
flags:
  python:
    paths:
      - python
    carryforward: true
  php:
    paths:
      - php
    carryforward: true
  javascript:
    paths:
      - javascript
    carryforward: true